name: Build

on:
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:
    branches: [ master ]
  #release:
  #  types: [published]

jobs:
  build-tauri-minimal:
    name: Build Tauri Minimal
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04,ubuntu-22.04-arm, windows-latest, macos-latest]
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0
  
      - name: Install Linux dependencies
        if: runner.os == 'Linux' 
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libgtk-3-dev xdg-utils
  
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
  
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
  
      - name: Install dependencies
        working-directory: aw-tauri
        run: npm install
  
      - name: Build Tauri app
        working-directory: aw-tauri
        run: |
          make prebuild
          make build
  
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build-${{ matrix.platform }}
          path: |
            aw-tauri/src-tauri/target/release/bundle/**/*.rpm
            aw-tauri/src-tauri/target/release/bundle/**/*.dmg
            aw-tauri/src-tauri/target/release/bundle/**/*.msi
            aw-tauri/src-tauri/target/release/bundle/**/*.deb
            aw-tauri/src-tauri/target/release/bundle/**/*.AppImage